import 'package:get/get.dart';

class LanguageKeys extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "changePassword": "Change Password",
          "old_pass": "Current Password",
          "new_pass": "New Password",
          "current_orders": "Current orders",
          "previous_orders": "Previous orders",
          "canceled_orders": "Canceled orders",
          "confirm_new_pass": "Confirm New Password",
          "change": "Change",
          "changeLanguage": "Change Language",
          "aed": "AED",
          "no": "No",
          "chooseLanguage": "Choose Language",
          "forgot_pass": "Forgot Your Password ?",
          "my_services": "My Services",
          "comments": "Comments",
          "enter_phone/mail":
              "Please Enter Your Email or Phone without country key",
          "phone/mail": "Email / Phone",
          "policies": "Application Policies",
          "add_product_success_message":
              "The product has been added successfully",
          "please_login": "Please login",
          "send": "Send",
          "settings": "Settings",
          "help": "Help",
          "rate_us": "Rate Us",
          "login_without_register": "Browse as a guest",
          "newArrival": "New Arrival",
          "myOrders": "My Orders",
          "addProductRate": "Add Your Rate",
          "myAddresses": "My Addresses",
          "support": "Support",
          "information": "Information",
          "legalInfo": "Legal Information",
          "giveFeedback": "Give feedback",
          "myPromoCodes": "My Promo Codes",
          "feedBack": "Feedback",
          "skip": "Skip",
          "no_services": "No SerVices !",
          "select_location": "Select Location",
          "edit_profile": "Edit Profile",
          "password": "Password",
          "update_services": "update Services",
          "update_photo": "Update photo",
          "notificationtype": "Notification Type",
          "to": "To",
          "from": "From",
          "brands": "Brands",
          "update": "Update",
          "productName": "Product Name",
          "please_select_location": "Please select  location",
          "add_location": "Add Location",
          "enter_city": "Enter your city",
          "signUp": "Sign Up",
          "invoiceNumber": "Invoice number",
          "StepOne": "Step one",
          "my_bundle": "My Bundle",
          "did_forget_pass": "Forgot Your Password ?",
          "googleLogin": "",
          "MyFav": "Favorite",
          "rateApp": "Rate app",
          "addYourRate": "Add Rate",
          "login": "Login",
          "popularBrands": "Popular brands",
          "bestSelling": "Best selling",
          "selling_products": "Selling products",
          "offers": "Offers",
          "login_by_social": "Login via Social Media",
          "have_no_acc_register": "Don't have an account ? ",
          "enter_new_pass": "Please Enter Your New Password",
          "photo_library": "Photo Library",
          "camera": "Camera",
          "upload_licence": "Upload Licence",
          "add_store_msg1":
              "You can add your own store to the 2020 commercial directory easily ..",
          "your_account_status_not_active": "Your Account Status Not Active",
          "my_fatoora": "My Fatoora",
          "family_desc":
              "The largest gathering to support and empower productive families",
          "add_image_validation": "Please make sure to add photos",
          "image_uploaded_successfully": "Image Uploaded successfully",
          "add_licence": "Add Licence",
          "register": "Register",
          "register2": "Register now",
          "confirm": "Confirm",
          "confirmOrder": "Confirm Order",
          "name": "Name",
          "userName": "UserName",
          "email": "Email",
          "phone": "Phone",
          "confirm_pass": "Confirm Password",
          "terms_agree": "Agree On Terms And Conditions",
          "save": "Save",
          "edit": "Edit",
          "search": "Search",
          "categories": "Categories",
          "super_market": "Supermarket",
          "fav": "Favorite",
          "favorites": "Favourites",
          "add_item": "Add to cart",
          "noCartItems": "Cart is Empty !!",
          "code": "Code",
          "orderProccess": "Preparing",
          "discount": "Discount",
          "distinguished_shops": "Featured shops",
          "verify": "Confirm",
          "enter-verification_code": "Please Enter Verification Code",
          "verification_code": "Verification Code",
          "youMustTry": "You Must Try It",
          "seeAll": "See all",
          "trending": "Trending",
          "save_wash_price": "And save on the price of washing",
          "cat_count": 'Categories count',
          "mainCat": "Main categories",
          "allCategories": "All Categories",
          "Communication_with_the_family": "Communication with the family",
          "profile": "Profile",
          "service": "Service",
          "delivery_speed": "Delivery Speed",
          "rate": "Rate",
          "choose_location": "Choose your location",
          "my_wallet": "My wallet",
          "my_cars": "My cars",
          "chat": "Chat",
          "createdAt": "Created at",
          "user_rate": "We Appreciate Your Feedback",
          "premium_places": "Premium places",
          "enter_phone": "Please Enter Your Phone",
          "enable_phone": "Activate Phone Number",
          "add": "Add",
          "browse_D2020": "Browse D2020",
          "input_data_validation_message":
              "Please make sure you added the correct data",
          "Add_a_product_to_sell": "Add a product to sell",
          "createAccount": "Create Account",
          "enterInfo": "Please Enter Your Name , Email , Password ",
          "confirmPass": "Confirm Password",
          "add_credit_card": "Add Credit Card",
          "month": "Month",
          "year": "Year",
          "card_no": "Card NO.",
          "cvv_no": "CVV/CVC NO.",
          "Add_productive_family_product": "Add a productive family product",
          "expiry_date": "Expiration Date ",
          "kilo_price": "Kg. Price",
          "sar": "SAR",
          "description": "Description",
          "quantity": "Quantity",
          "saved_places": "Saved places",
          "my_points": "My points",
          "add_store_msg2":
              " All you have to do is contact the D2020's customer service via whatsApp or call and provide them with store information ",
          "weight": "Weight",
          "additions": "Packaging type",
          "notes": "Notes",
          "continue_shopping": "Continue Shopping",
          "continue": "Continue",
          "payment": "Payment",
          "pay": "pay",
          "my_details": "My Details",
          "select_payment_method": "Select Payment Method",
          "total": "Total",
          "subtotal": "SubTotal",
          "my_products": "My Products",
          "show_all": "Show All",
          "new_orders": "New Orders",
          "reserve_product": "Reserve product",
          "explore": "Explore",
          "noResult": "No Result !!!",
          "change_language": "Change Language",
          "packages": "Packages",
          "change_password": "change password",
          "ProductDetails": "Product Details",
          "choose_payment": "Choose payment method",
          "delivery_fee": "Delivery Fees",
          "location": "Your location",
          "gift_value": "Enter the gift value.",
          "rental_onBoarding": "With the rental department",
          "items_price": "Subtotal",
          "count": "Count",
          "update_selling_product": "Update selling product",
          "price": "Price",
          "time_date_validation": "Make sure to add the time and date",
          "Yes": "Yes",
          "cart": "Cart",
          "check_out": "Check out",
          "create_order": "Create order",
          "no_favorite": "No Favorite Products !! ",
          "orderTracking": "Order Tracking",
          "delivery": "Delivery",
          "cooking": "Cooking",
          "edit_store": "Edit Store",
          "Add_booking_location": "Add a booking location",
          "goToMap": "Go To Map",
          "addressName": "Address Name",
          "fully_booked": "Fully booked",
          "choose_another_times":
              "Choose another date or check our discounted times",
          "orderDatails": "Order Details",
          "biker_hint":
              "The biker can find your vehicle easier without calling.",
          "addToCart": "Add To Cart",
          "continue_order": "Continue Order",
          "address": "Address",
          "write_message": "Write your message",
          "change_or_add": "Change / Add",
          "wallet": "Wallet",
          "agrre": "أوافق",
          "about_drizzle": "About drizzle",
          "balance_due": "Balance",
          "enter_mount": "Enter the amount you want to charge",
          "how_to_use_drizzle": "How to use drizzle ?",
          "have_gift": "Do you have a gift? Apply it now",
          "add_site": "Add a new location",
          "previous_oper": "Previous operations",
          "whatsApp_contact": "Communication via WhatsApp",
          "payment_on_arrival": "Cash On Delivery",
          "recharge": "Recharge",
          "view_update_account": "View an edit account information",
          "Products": "Products",
          "drizzle_plus_wash": "Drizzle Plus Wash",
          "use": "Use",
          "privacy": "Privacy policy",
          "order_num": "Order Number",
          "my_packages": "My packages",
          "orders": "Orders",
          "hello": "Hello",
          "add_promo_code": "Add promo code",
          "Shopkeeper": "Shopkeeper",
          "stopTune": "Stop opening tune",
          "car_details": "Car Details",
          "additional_services": "Additional services",
          "date_time": "date and time",
          "date_and_time": "Date and time",
          "choose_localtion": "Choose location",
          "reservations": "Reservations",
          "verify_2": "Enter",
          "logout": "Logout",
          'bank_name': 'Bank name',
          "no_gifts": "No gifts found",
          "no_reservations": "There are no reservations at the moment",
          "all_packages": "All packages",
          "show_location_map": "Show location on map",
          "gender": "Gender",
          "the_best": "The best",
          "dirizzle_services": "Drizzle sevices",
          "dark_mode": "Dark mode",
          "order_button": "Order",
          "Kingdom_level": "Kingdom level",
          "exit_app_title": "Exit App",
          "gifts_phone": "Send the gift to the phone number",
          "brand": "Car brand",
          "car_volum": "Car volum",
          "choose_from": "Choose from",
          "Schedule": "Schedule",
          "wash_packages": " Wash packages ",
          "Add_car": "Add your Car",
          "please_select_car": "Please select a car",
          "choose_care_model": "Choose your car model ",
          "search_car_mode": "Search for car model",
          "car_color": "Car color",
          "car_brand": "Car brand",
          "save_your_location": "Save your location",
          "add_gifts_validation":
              "Please make sure to add the gift value, message, phone number, and name.",
          "exit_message": "Are you sure to log out?",
          "food_offers": "Food Offers",
          "wash": "wash",
          "confirm_order": 'Confirm order',
          "counter_message":
              "Please confirm the order before completing the counter",
          "home_care_offers": "House Keeping Offers",
          "fashion_offers": "Fashion Offers",
          "There_are_no_requests_yet": "There are no requests yet",
          'suitable_price': " as appropriate for you ",
          "send_wash": " Send gift washes ",
          "my_orders": "My orders",
          "my_facilities": "My facilities",
          "available_offer": "Available Offer",
          "voice_order": "Voice Order",
          "account_type": "Account type",
          "Add_personal_photo": "Add a personal photo",
          "no_notifications": "You don't have any notification yet",
          "update_profile": "Update profile",
          "edit_image": "Edit profile image",
          "order_number": "Order #",
          "in_delivery": "Shipping",
          "subject": "Subject",
          "message": "Message",
          "out_for_delivery": "Shipping",
          "delivered": "Delivered",
          "English_title_(optional)": "English title (optional)",
          "record_ur_order": "Please Record Your Order",
          "details": "Details",
          "date": "Date",
          "your_account_not": "Yor account not active",
          "no_pics_added": "No images added",
          "rents_products": "Rents product",
          "update_store_images": "Update store images",
          "add_more_images": "Add more images",
          "welcome_to_d2020": "Welcome to the D2020 Guide!",
          "order_summery": "Order Summary",
          "no_search_result": "There is no search result !!",
          "Home": "Home",
          "Offers": "Offers",
          "give_your_location_name":
              "Give your location a name (home-work-etc.)",
          "car_validations": "Make sure to add the vehicle",
          "available_times": "Available appointments on this date",
          "order_tracking": "Reservation tracking",
          "Sortـby": "Sort by",
          "add_product": "Add product",
          "ar_name": "Name in arabic",
          "payment_completion": "Payment completion",
          "en_name": "English name",
          "ar_desc": "Description in Arabic",
          "en_desc": "English description (optional)",
          "rents_filter": "Rents Filter",
          "gifts": "Gifts",
          "addpromo": "You Can use a promo code provided",
          "sale_onboarding": "with the sales department",
          "reservation_number": "Reservation number",
          "add_new_car_hint": 'Select model, brand and car',
          "more": "More",
          "addPromoCode": "Add new Promo code",
          "no_notifications": "There are currently no notifications",
          "no_stores_in_account": "",
          "maximum": "Maximun value",
          "activePromo": "Active Promo Codes",
          "usedPromo": "Used Promo Codes",
          "search_for_location": "Search for location",
          "biker_rate": "Your rating of the biker",
          "deliverTo": "Drive to",
          "payment_method2": "Payment method",
          "minimum": "Minimum value",
          "stores_search": "Stores search",
          "main_category": "Main Category",
          "Add_a_product_for_rent": "Add a product for rent",
          "common_qs": "FAQ's",
          "search_by_keywords": "Search by Keywords",
          "terms_cons": "Terms And Conditions",
          "agree": "Agree",
          "current": "Current",
          "previous": "Previous",
          "canceled": "Canceled",
          "Added_by": "Added by",
          "MyAdderesses": "My Adresses",
          "from_time_to": 'From 10 am: 12 pm',
          "plate_number": "Plate number",
          "optional": "Optional",
          "payment_details": "Payment details",
          "The_largest_collection_of_shops": "The largest collection of shops",
          "myPromo": "My Promo Codes",
          "biker_notes": "notes for Biker",
          "enter_promo_code": "Enter the promo code here...",
          "orderStatus": "Order Status",
          "supportMessage": "How Can We Help You ?",
          "highest_rated": "Highest rated",
          "buy": "Buy",
          "Shops_by_city": "Shops by city",
          "the_closest": "The closest",
          "Saudiـarabia": "Saudi Arabia",
          "giveFeedBc": "Give Feedback",
          "main_classify": "Main Classification",
          "locate_deliver_address": "Locate Address For Delivery",
          "one_riyal_wash": "One sar per wash",
          "shop": "Shop",
          "package_details": "Package details",
          "monthes": "months",
          "your_location": 'Your location',
          "reservation_details": "Reservation details",
          "family_filter_result":
              "result of the Filteration of productive families",
          "addresses_list": "Addresses List",
          "deliver_to_another_location": "Deliver to Another Location",
          "locate_on_map": "Choose Location on Map",
          "sale_filter": "Sale Filter",
          "deliver_to_current": "Deliver to Current Location",
          "enable_gps": "Enable Location Services (GPS)",
          "track_orders": "Track Orders",
          "canceled": "Canceled",
          "ordered": "Ordered",
          "classification": "Category",
          "info": "Information",
          "cancel_reason": "Cancellation Reason",
          "exit_app": "Do you want to exit an App?",
          "back": "Back",
          "full_name": "Full name",
          "ads_title": "Advertisment title",
          "address_details": "Address Details",
          "regions": "Region",
          "additional_address": "Additional Address (Optional)",
          "address_type": "Address Type",
          "delivery_times": "Delivery times",
          "family_products": "Family products",
          "city": "City",
          "add_new_car": "Add a new car",
          "change_car": "Change car",
          "price_before_discount": "price before discount",
          "street": "Street",
          "block": "Building",
          "personal_info": "personal information",
          "floor": "Floor",
          "flat": "Flat",
          "add_other_directions": "Add Another Directions (Optional)",
          "required": "(Required)",
          "what_we_offer": "What do we offer ?",
          "additional_phone_num": "Additional Phone Number (Optional)",
          "distinctive_sign": "Landmark (Optional)",
          "family_onboarding": "With the productive families department",
          "select_ur_location": "Check Your Location",
          "locate": "Locate",
          "For_rent": "For Rent",
          "addresses": "Addresses",
          "about": 'About',
          "prev_orders": "Previous Deals",
          "track_last_orders": "Track Last Order",
          "liked_products": "Liked Products",
          "credit_card": "Credit Card",
          "It_is_closed_at_prayer_time": "It is closed at prayer time",
          "language": "Language",
          "call_us": "Call Us",
          "terms": "Application terms",
          "popularQ": "Popular Questions",
          "special_offers": "Special Offers",
          "delete_account": "Delete account",
          "add_store": "Add store",
          "contactUs": "Contact Us",
          "prev_ordinary_orders": "Ordinary Orders",
          "prev_voice_order": "Voice Orders",
          "state": "Status",
          "Containsـoffers": "Contains offers",
          "newest": "The Newest",
          "appLogo": "App Logo",
          "categoryName": "Water",
          "stores_filter": "Stores filter result",
          "filter": "Filter",
          "itemName": "Product Name",
          "filter": "Filter",
          "filter_by": "Filter by",
          "noOrders": "No Current orders",
          "no_addresses_added": "No addresses added",
          "you_are_welcome_in": "you are welcome in",
          "noProducts": "No products ...",
          "donepayment": "Successfull payment process",
          "tradeMark": "Trade Mark",
          "no_canceled_orders": "No canceled orders",
          "category": "Category",
          "updateProductRate": "Update your rate",
          "inprogress": "Preparing",
          "exit": "Exit",
          "The_address_is_Arabic": "The address is Arabic",
          "It's_not_available_now": "It's not available now",
          'There_is_no_search_result': "There is no search result",
          "branches": "branches",
          "no_products_added_yet": "No products added yet",
          "branch_units": "Branch units",
          "shop_now": "Shop now",
          "profile_image": "Profile Picture",
          "get_new_Pass": "Get a new password",
          "browse_as_visitor": "Browse as a visitor",
          "Please_login": "Please Login",
          "login_now": "Login Now",
          "color": "Color",
          "size": "Size",
          "Views": "Views",
          "reset": "Reset",
          "done": "Done",
          "added_in": "Added in",
          "Add_origin": "Add origin",
          "notificationContent": "This is a notification for you",
          "notificationTime": "10 Minutes ago",
          "languageSwitch": "العربية",
          "all": "All",
          "suggested": "Suggested products",
          "There_are_currently_no_ratings": "There are currently no Categories",
          "hotDrinks": "Hot Drinks",
          "rice": "Rice",
          "pasta": "Pasta",
          "snacks": "Snacks",
          "goToHome": "Go to Home Screen",
          "notifications": "Notifications",
          "congrates": "Congratulations !",
          "Category": "Category",
          "subCategory": "Subcategory",
          "Add_a_facility":
              "Add a facility to your account now and enjoy the best offers",
          "add_productive_family": "Add productive family",
          "add_video": 'Add video',
          "add_stores": "Add stores",
          "send_gifts": "Send gifts",
          "previous_Gifts": "Previous gifts",
          "add_pics": "Add Picture",
          "thanks": "Thanks for shopping ",
          "itemDetails":
              "Three items of Chips Lays get one free from any market on our application",
          "personal_info": "Personal Information",
          "vat": "VAT",
          "other_fees": "Other Fees",
          "total_discount": "Total Discount",
          "soon": "This Service will be available soon !",
          "ok": "OK",
          "available_product": "Available Product",
          "addresses_type": "Address Type",
          "price_on_selection": "Price depends on selection",
          "choose": "Choose Area",
          "noData": "There are no items",
          "noOffers": "There are no offers right now",
          "pending": "Pending",
          "orderDone": "Order submitted ",
          "inProgress": "In Progress",
          "The_price_after_discount": 'The price after discount',
          "Add_photos": "Add photos",
          "shipped": "Shipped",
          "user": "User",
          "latest_offers": "Latest offers and discounts",
          "canceledFromUser": "Canceled From User",
          "canceledFromStore": "Canceled From Store",
          "stores": "Stores",
          "car": "Car",
          "visa": "Visa",
          "select_options_first": "Please select options first !",
          "select_options_first_content":
              "all options has to be selected before adding to cart",
          "added_to_cart": "Item added to cart !",
          "yes": "Yes",
          "u_sure_to_change_password":
              "Are you sure you want to change_password ?",
          "cancellation_reason": "Cancellation Reason",
          "cancel": "Cancel",
          "cash": "Cash On Delivery",
          "communication": "Communication",
          "u_have": "You Have",
          "no_more_products": "No more products to load",
          "no_more_notifications": "No more notifications to load",
          "swipe_up": "Swipe up",
          "return_order": "Return Order",
          "times_of_work": "Times of work",
          "slide": "swipe left to remove a product",
          "notEmpty": "Data must be filled",
          "delete": "Delete",
          "noNotification": " There are no Notification",
          "returned": "Returned",
          "reason": "Cancellation reason",
          "no_previous_orders": "No previous orders ",
          "share_app": "Share App",
          "share_app_message":
              "You can share the application with your friends",
          "share_now": "Share Now",
          "delivery_notes":
              "Notes: Dear user, please note that the delivery process by us will take from 2 working days to a maximum of 5 working days",
          "whatsapp_reach": "Reach us via WhatsApp",
          "tax": "Tax",
          "returnReason": "Return reason",
          "message_sent":
              "Your message has been sent, We will contact you soon.",
          "voice_order_sent":
              "Your voice order has been sent and it will be proceeded.",
          "rate_sent": "Your feedback has been sent, Thanks",
          "no_order": "No orders yet !",
          "current_balance": "Current balance: ",
          "saved": "saved! please choose to send or delete",
          "error": "Error!",
          "rent_type": "Rent type",
          "new_user_message": "Are you new to D2020",
          "low_wallet_balance": "Wallet balance is not sufficient",
          "delivery_place": "Delivery/Collect place",
          "delivery_to_add": "Deliver to your location",
          "collect_from_store": "Collect from store",
          "shipping_comp": "Shipping company",
          "choose_comp": "Choose",
          "choose_store_to_collect": "Choose store to collect from",
          "delivery_value": "Fees:",
          "enable_location": "Please enable GPS in your device",
          "out_of_stock": "Out of stock",
          "notify_when_avi": "Notify me when available",
          "will_be_notified": "You will be notified",
          "connectivity": "Please Connect to the Internet",
          "termsAndConditions": "Terms and Conditions",
          "replacementPolicies": "Replacement Policies",
          "returnPolicies": "Return Policies",
          "similiar": "Similar Products",
          "work": "Work",
          "home": "Home",
          "replace": "Replace",
          "writeReplacementNotes": "Please enter your reasons",
          "selectStore": "Please select branch",
          "addLocation": "Add new location",
          "delete_confirmation": "Are you sure you want to delete this item ?",
          "show_on_map": "Show on Maps",
          "showMore": "Show More",
          "country": "Country",
          "wantToDelete": "Do you want to delete this location ?",
          "deleteAccount": "Do you want to delete the account ?",
          "next": "Next",
          "add_new_address": "Add new address",
          "label_address_example": "Label the address, e.g., (Home, Work)",
          "step1_of_3": "Step 1 of 3",
          "step2_of_3": "Step 2 of 3",
          "step3_of_3": "Step 3 of 3",
          "step": "step",
          "of": "of",
          "signIn": "Sign In",
          "submit_order": "Submitting order",
          "submit": "Submit",
          "choose_shipment_or_collect":
              "Please choose shipment/collect method to proceed",
          "chooseAddress": "please choose Address",
          "notExist": "No Coupon",
          "no_address": "No address selected !!",
          "choose_branch": "Please choose branch to collect from",
          "exist": "Coupon submitted",
          "giveLocationPermission":
              "Please make sure you enable Location in your phone",
          "loginWithGoogle": "Login With Google",
          "loginWithfb": "Login With Facebook",
          "loginWithApple": "Login With Apple",
          "track": "Track order",
          "Track": "Track order",
          "choose_address": "Choose the address",
          "cod_fees": "COD Fees",
          "delivery_within": "Delivery within",
          "day": "days",
          "cant_change_password":
              "Sorry, you can't change your password when your logged via social media apps",
          "shipping_fee": "Shipping fees ",
          "continueToHistory": "Go To My Orders",
          "phoneWithoutKey": "Phone without country key",
          "resend": "Resend",
          "chargeWallet": "Charge Wallet",
          "chargeValue": "Charge Value",
          "minCharge": "Minimum Recharge amount is ",
          "agreeTerms": "You should agree Terms & Conditions",
          "goToWallet": "Go To Wallet",
          "login_with_bio": "Login with fingerprint",
          "enable_finger_print": "Login with fingerprint",
          "or": "OR",
          "touch_to_login": "Place your finger on the sensor to login",
          "pls_enter_pass": "Please enter your password",
          "touch_to_verify": "Place your finger to verify",
          "disable_fingerprint": "Disable fingerprint login",
          "touch_to_use_wallet": "Using wallet to pay",
          "fingerprint_not_working":
              "Fingerprint is not working correctly on this device",
          "chargeIsDone": "Wallet balance charged successfully!",
          "success": "Added successfully!",
          "deliverToThisPlace": "Your order will be delivered to here",
          "enter_otp": "Enter OTP",
          "retry": "Re-Try",
          "confirm-payment": "Confirm Payment",
          "totalBeforeDiscount": "before discount",
          "totalAfterDiscount": "after discount",
          "tamayouz": "STC discount for Tamayouz members",
          "noDicountNow": "Discount not available",
          "includeVat": "include Vat",
          "userGuest": "Continue as a Guest",
          "registerNow": "You can register now",
          "sendSms": "You will recieve an SMS on this number",
          "hagVisa": "Hajj Visa",
          "accepted": "Accepted",
          "services": "Services",
          "bestExperience": "Best Experience",
          "newFeeds": "Latest News",
          "TourismPlaces": "TourismPlaces",
          "hajAndOmra": "hajj and Umrah",
          "consulate": "Consular services",
          "others": "other services",
          "Surveys": "Surveys",
          "check_out2": "Payment",
          "vip": "VIP",
          "normal": "Normal",
          "order_prepared": "Your order has been prepared",
          "order_received_by_courier":
              "The order has been received by the courier",
          "order_on_the_way": "Your order is on the way",
          "order_delivered": "The order has been delivered",
          "vipDescription":
              "Do everything from your place where our representative will deliver you wherever you are",
          "normalDescription":
              "You can set an appointment in advance before going to the company",
          "Residence": "Residence",
          "expand": "Residence extension",
          "requiredPapers": "The required paperwork",
          "readDocument": "Please read the following file before starting",
          "instructions": "Instructions",
          "application": "Application",
          "fillApplication": "Please fill in the following information",
          "profilePic": "Profile Picture",
          "personalPhoto": "Photograph",
          "firstName": "first name",
          "fatherName": "father name",
          "grandPa": "grandfather name",
          "family": "family",
          "passportNo": "passport number",
          "passportType": "passport type",
          "passportPlace": "Passport Place",
          "passportDate": "Passport Date",
          "passportExpiryDate": "Expiry Date",
          "dateOfBirth": "Date Of Birth",
          "placeOfBirth": "Place Of Birth",
          "nationalId": "NationalId",
          "nationality": "Nationality",
          "exNationality": "Ex-Nationality",
          "insideTourism": "Domestic Tourism",
          "outsideTourism": "Foreign Tourism",
          "visaType": "Visa Type",
          "representing": "Representing in",
          "personal/intityName": "Person/The requesting party Name",
          "personal/intityAddress": "Person/The requesting party Address",
          "id/business/Number": "National Id/Residence/Commercial Register",
          "authority": "Destination",
          "distinction": "Distinctions",
          "completeApplication": "completeApplication",
          "insuranceCompany": "select Insurance Company",
          "chooseCompany": "choose Company",
          "choosePhoto": "choosePhoto",
          "prevDeals": "Pre",
          "gifts": "Gifts",
          "gifts2": "Gifts",
          "trips": "Trips",
          "welcome": "welcome",
          "essays": "Articles",
          "essays2": "Articles",
          "umrahOrder": "Umrah Order",
          "badalUmrahOrder": "Order Umrah Badal",
          "orderType": "Order Type",
          "forYou": "For You",
          "verify_phone_password":
              "Please ensure that you have added your phone number and password",
          "forSomeOne": "For Someone else",
          "UmrahInfo": "Information of the person to perform Umrah",
          "moreUmrahDetails": "More Details",
          "umrahDetails": "Umrah Details",
          "gender": "Gender",
          "offersFrom": "Offers From",
          "accept": "Accept",
          "orderDetails": "Order Details",
          "serviceProviderProfile": "Provider Details",
          "time": "time",
          "age": "Age",
          "best_sales": "Best sales",
          "reviews": "Reviews",
          "tripProvider": "Trip Provider",
          "ordersNumber": "Orders Number",
          "theـbestـrentals": "The best rentals",
          "delegates": "Delegates",
          "recent_requests": "Recent requests",
          "essayDetails": "Article Details",
          "report": "report",
          "close": "close",
          "distinguished_productive_families":
              "Distinguished productive families",
          "add_report": " add report",
          "Write_Your_Report": "Write your report",
          "reportReason": "report reason",
          "reported": "reported",
          "waiting": "Waiting provider to accept",
          "noEssays": "There are no Articles yet",
          "sureToConfirm": "Are you sure you want to confirm order ?",
          "ehram": "الاحرام",
          "male": "male",
          "female": "female",
          "Welcome_message": "you are welcome in",
          "login_validation_message": "Please verify the data",
          "guestUser": "Guest User",
          "canLogin": "you can login now",
          "yourMessage": "write your message",
          "check": "Please check data",
          "orderReason": "Umrah reason",
          "otherReason": "Other reason",
          "choosePayment": "choose payment method",
          "downloadCertificate": "Download the certificate",
          "paymentDeatils": "Payment Details",
          "confirmation": "Confirm",
          "wash": "Wash",
          "sale": "For Sale",
          "verify_phone_password_email":
              "Please make sure to provide your phone number, password, and email address",
          "sell_desc": "Sell ​​your products in the largest directory",
          "garage": "Garage",
          "recovery": "Recovery",
          "get_new_password": "Get a new password",
          "wheels": "Wheels",
          "cars": "Cars",
          "rentalOffices": "Rental Offices",
          "rent": "For Rent",
          "spareParts": "Spare Parts",
          "canceledOrder": "Cancele order",
          "carPaint": "Car Paint",
          "account": "Account",
          "mechanical": "Mechanical",
          "electrical": "Electrical",
          "fixedServices": "Shop Service",
          "rental_office_name": "Rental Office Name",
          "deliveryService": "Home Service",
          "accessories": "Accessories",
          "no_results": "No results Found ...!",
          "company": "Company",
          "selectBundle": "Please select Bundle",
          "car_name": "Car Name",
          "Notes": "Notes",
          "car_model": "Car Model",
          "got_me": "got me",
          "car_type": "Car Type",
          "fill_form": "Please fill empty fields",
          "find_company": "Find Company",
          "request": "Request",
          "available_cars": "Available Cars",
          "whats_app": "WhatsApp Number",
          "dubai": "Dubai",
          "store": "Store",
          "hi": "Hello",
          "latest_products": "The latest products",
          "wash_fixed_services": "wash in the garage",
          "wash_delivery_service": "Wash in the home",
          "prod_family": "Productive family",
          "delegates_onboarding": "with delegates department",
          "Search_products_for_sale": "Search products for sale",
          "ar_rams": "Ar-Rams",
          "all_orders": "All orders",
          "track_order": "Track order",
          "productive_families": "productive families",
          "al_madam": "Al Madam",
          "product_details": "Product details",
          "add_rate": "Add rate",
          "item_deleted": "Deleted successfully",
          "update_success": "Updated successfully",
          "rental_search": 'Search rental products',
          "company_added_successfully":
              "company added successfully, please login",
          "complete_address_info":
              "Please make sure to enter the full address details",
          "add_wallet_balance": "Add balance to wallet",
          "wallet_balance": "Wallet balance",
          "wallet_balance_cost": "Add balance",
          "transactions": "Transactions",
          "whatsapp": "WhatsApp",
          "phone_call": "Phone call",
          "payment_method": "Payment method",
          "discount_coupon": "Discount coupon",
          "add_discount_coupon": "Add discount coupon",
          "products_cost": "Products cost",
          "price_after_discount": "Price after discount",
          "follow_up": "Continue",
          "no_sections_currently": "No sections currently",
          "add_to_cart": "Add to cart",
          "delivery_time2": "Delivery time",
          "order_price": "Order price",
          "already_have_account": "Already have an account ? ",
          "remember_me": "Remember me",
          "sign_up": "Sign up",
          "enter_code_sent_to_phone":
              "Please enter the code sent to your phone",
          "resend_code": "Resend code",
          "guest_login": "Login as guest",
          "app_issues_contact":
              "If you encounter any issues using the app, please contact us at \nvia WhatsApp or phone call",
        },
        'ar': {
          "phone_call": "الاتصال",
          "guest_login": "الدخول كزائر",
          "resend_code": "اعادة ارسال الكود",
          "delivery_time": "زمن الوصول",
          "enter_code_sent_to_phone": "برجاء ادخال الكود المرسل لجوالك",
          "remember_me": "تذكرني",
          "order_price": "سعر الطلب",
          "sign_up": "تسجيل جديد",
          "delivery_time2": "زمن الوصول",
          "add_to_cart": "اضف الي السلة",
          "no_sections_currently": "لا يوجد أقسام حاليا",
          "follow_up": "متابعة",
          "price_after_discount": "السعر بعد الخصم",
          "products_cost": "تكلفة المنتجات",
          "add_discount_coupon": "قم بإضافة كوبون الخصم",
          "discount_coupon": "كوبون خصم",
          "payment_method": "طريقة الدفع",
          "transactions": "المعاملات",
          "whatsapp": "واتس اب",
          "app_issues_contact":
              "في حالة وجود مشاكل في استخدام التطبيق برجاء التواصل مع الرقم \nعبر واتس اب او الاتصال",
          "contact_support": "التواصل مع الدعم",
          "wallet_balance_cost": "قيمة الشحن",
          "wallet_balance": "رصيد المحفظة",
          "add_wallet_balance": "إضافة رصيد للمحفظة",
          "no_addresses_added": "لا يوجد عناوين مضافة",
          "changePassword": "تغيير كلمة المرور",
          "old_pass": "كلمة المرور القديمة",
          "all_orders": "جميع الطلبات",
          "shop_now": "تسوق الان",
          "new_pass": "كلمة المرور الجديدة",
          "rental_search": 'بحث منتجات الإيجار',
          "no_products_added_yet": "للأسف لم تقم بإضافة أي منتجات حتي الان",
          "get_new_Pass": "الحصول على كلمة المرور",
          "confirm_new_pass": "تأكيد كلمة المرور الجديدة",
          "confirmPass": "تأكيد كلمة المرور",
          "change": "تغيير",
          "brands": "الماركات",
          "comments": "التعليقات",
          "account_type": "نوع الحساب",
          "city": "المدينة",
          "changeLanguage": "تغيير اللغة",
          "please_login": "برجاء تسجيل الدخول",
          "current_orders": "الطلبات الحالية",
          "previous_orders": "الطلبات السابقة",
          "canceled_orders": "الطلبات الملغية",
          "add_productive_family": "إضافة أسرة منتجة",
          "prod_family": "أسرة منتجة",
          "chooseLanguage": "اختر اللغة",
          "forgot_pass": "نسيت كلمة المرور",
          "enter_phone/mail": "من فضلك ادخل رقم الجوال او البريد الالكتروني",
          "phone/mail": "البريد / الجوال",
          "send": "ارسال",
          "seeAll": "الكل",
          "settings": "الإعدادات",
          "latest_products": "اخر المنتجات",
          "help": "المساعدة",
          "rate_us": "قيمنا",
          "add_stores": "إضافة محلات",
          "bestSelling": "الأكثر مبيعا",
          "orderProccess": "تجهيز الطلب",
          "offers": "العروض",
          "aed": "درهم",
          "skip": "تخطي",
          "order_num": "رقم الطلب",
          "createdAt": "تاريخ الإضافة",
          "deliverTo": "توصيل الي",
          "addToCart": "أضف إلى العربه",
          "ProductDetails": "تفاصيل المنتج",
          "myOrders": "طلباتي",
          "productName": "اسم المنتج",
          "noOrders": "لا يوجد طلبات حاليا !!",
          "noProducts": "لا يوجد منتجات حاليا",
          "donepayment": "تم الدفع بنجاح",
          "myAddresses": "العناوين",
          "feedBack": "Feedback",
          "category": "القسم",
          "already_have_account": "لديك بالفعل حساب ؟",
          "verify_phone_password_email":
              "برجاء التأكد من إضافة رقم الجوال و كلمة المرور والبريد الالكتروني",
          "hi": "هلا",
          "updateProductRate": "تحديث التقييم",
          "Welcome_message": "أهلاً بك في",
          "new_user_message": "هل أنت جديد على D2020",
          "support": "الدعم الفني",
          "exit": "خروج",
          "logout": "تسجيل الخروج",
          "privacy": "سياسة الخصوصية",
          "order_prepared": "تم تجهيز طلبك",
          "order_received_by_courier": "تم استلام الطلب من المندوب",
          "order_on_the_way": "طلبك في الطريق",
          "order_delivered": "تم تسليم الطلب",
          "exit_message": "هل أنت متأكد من تسجيل الخروج ؟",
          "myPromoCodes": "أكواد الخصومات",
          "legalInfo": "المعلومات القانونية",
          "giveFeedback": "أضف تقيمك",
          "trending": "الأكثر شيوعاً",
          "login_without_register": "دخول بدون تسجيل",
          "youMustTry": "لا بد أن تجرب",
          "googleLogin": "تسجيل الدخول بواسطة جوجل",
          "password": "كلمة المرور",
          "did_forget_pass": "هل نسيت كلمة المرور ؟",
          "mainCat": "الأقسام الرئيسية",
          "login": "تسجيل الدخول",
          "the_best": "الأفضل",
          "change_password": "تغيير كلمه السر",
          "login_by_social": "الدخول بواسطة وسائل التواصل الاجتماعي",
          "have_no_acc_register": "ليس لديك حساب؟  ",
          "have_acc_login": "لديك حساب؟ ",
          "enter_new_pass": "من فضلك ادخل كلمة المرور الجديدة",
          "register2": "سجل الآن",
          "register": "تسجيل",
          "popularBrands": "ماركات مشهوره",
          "confirm": "تأكيد",
          "MyFav": "المفضلة",
          "check_out": "الدفع",
          "check_out2": "الدفع",
          "create_order": "إضافة طلب",
          "no_search_result": "لا يوجد نتيجة للبحث",
          "maximum": "الحد الأقصي",
          "no_favorite": "لايوجد منتجات ",
          "addYourRate": "أضف تقيمك ",
          "rateApp": "قيم التطبيق",
          "confirmOrder": "إتمام الطلب",
          "name": "الاسم",
          "userName": "اسم المستخدم",
          "email": "البريد الالكتروني",
          "phone": "رقم الجوال",
          "verify_phone_password":
              "برجاء التأكد من إضافة رقم الجوال و كلمة المرور",
          "confirm_pass": "تأكيد كلمة المرور",
          "terms_agree": "اوافق على الشروط و الاحكام",
          "save": "حفظ",
          "edit": "تعديل",
          "search": "بحث",
          "verify": "تفعيل",
          "exit_app_title": "الخروج من التطبيق ",
          "code": "الكود",
          "camera": "الكاميرا",
          "add_licence": "إضافة تصريح",
          "upload_licence": "إضافة التصريح",
          "The_largest_collection_of_shops": "أكبر تجمع محلات",
          "Kingdom_level": "على مستوى المملكة والإمارات",
          "store": "محل",
          "edit_profile": "تعديل الصفحةالشخصية",
          "label_address_example": "قم بتسمية العنوان مثال: (المنزل, العمل)",
          "update_services": "تحديث الخدمات",
          "your_account_status_not_active": "حسابك غير مفعل",
          "my_services": "خدماتي",
          "no_services": "لاتوجد خدمات",
          "packages": "الباقات",
          "select_location": "إختر الموقع",
          "please_select_location": "برجاء إختيار الموقع",
          "my_bundle": "باقتي",
          "image_uploaded_successfully": "تم إضافة الصورة بنجاح",
          "enter-verification_code": "ادخل كود التفعيل",
          "verification": "التفعيل",
          "service": "الخدمة",
          "rate": "تقييم",
          "stores": "المحلات",
          "gender": "النوع",
          "enter_phone": "ادخل رقم الجوال",
          "enable_phone": "تفعيل رقم الجوال",
          "no_previous_orders": "لا يوجد طلبات سابقة",
          "add": "اضافة",
          "brand": "الماركة",
          "continue": "متابعة",
          "please_select_car": "برجاء اختيار السيارة",
          "add_new_car": "إضافة سيارة جديدة",
          "dirizzle_services": "خدمات دريزل",
          "add_credit_card": "اضافة بطاقة إئتمان ",
          "month": "الشهر",
          "year": "السنه",
          "card_no": "رقم الكارت",
          "cvv_no": "CVV/CVC رقم",
          "expiry_date": "  تاريخ الانتهاء",
          "delivery_times": "مواعيد التسليم",
          "sar": "ريال",
          "notes": "ملاحظة",
          "distinguished_shops": "محلات مميزة",
          "payment": "الدفع",
          "theـbestـrentals": "أفضل الإيجارات",
          "agrre": "أوافق",
          "cart": "السلة",
          "complete_address_info":
              "الرجاء التأكد من إضافة بيانات العنوان كاملة",
          "my_products": "منتجاتي",
          "show_all": "اظهر الكل",
          "new_orders": "طلبات جديدة",
          "choose_from": "اختر من",
          "canceled": "تم الإلغاء",
          "reserve_product": "حجز المنتج",
          "track_order": "متابعة الطلب",
          "orderStatus": "حالة الطلب",
          "address": "العنوان",
          "giveFeedBc": "من فضلك ضع تقيمك",
          "choose_payment": "من فضلك اختر طريقة الدفع المناسبة لك",
          "payment_list": "قائمة باجمالى المصاريف المطلوبة",
          "wallet": "المحفظة",
          "hello": "مرحبا",
          "stopTune": "إيقاف النغمة الإفتتاحية",
          "Add_booking_location": "إضافة موقع الحجز",
          "fully_booked": "محجوز بالكامل",
          "verify_2": "ادخال",
          "order_button": "اطلب",
          "date": "التاريخ",
          "Home": "الرئيسية",
          "MyAdderesses": "عناويني",
          "myPromo": "أكواد الخصومات",
          "about_drizzle": "عن دريزل",
          "about": 'من نحن',
          "explore": "إكتشف",
          "total": "المجموع",
          "inprogress": "جاري التحضير",
          "delivered": "تم التوصيل",
          "no_reservations": "لا يوجد حجوزات في الوقت الحالي",
          "branches": "الأفرع",
          "Saudiـarabia": "السعودية",
          "branch_units": "وحدات الأفرع",
          "Offers": "العروض",
          "more": "المزيد",
          "common_qs": "الاسئلة الشائعة",
          "terms_cons": "الشروط و الاحكام",
          "you_are_welcome_in": "أهلاً بك في",
          "ar_name": "الإسم عربي",
          "locate_deliver_address": "حدد مكان التوصيل",
          "shop": "تسوق",
          'bank_name': 'إسم البنك',
          "how_to_use_drizzle": "كيف تستخدم دريزل ؟",
          "addpromo": "يمكنك أستخدام اكواد الخصومات",
          "addPromoCode": "من فضلك أضف كود الخصم ",
          "activePromo": "الأكود الحالية",
          "usedPromo": "الأكواد المستخدمة",
          "addresses_list": "قائمة العناوين",
          "your_account_not": "الحساب غير مفعل",
          "location": "الموقع",
          "payment_completion": "اتمام الدفع",
          "choose_address": "اختر العنوان",
          "deliver_to_another_location": "التوصيل الى عنوان اخر",
          "locate_on_map": "اختر الموقع على الخريطة",
          "deliver_to_current": "التوصيل الى الموقع الحالي",
          "subtotal": "المجموع الجزئي",
          "supportMessage": "كيف نستيع تقديم المساعدة ؟",
          "paymentDeatils": "تفاصيل الدفع",
          "confirmation": "التأكيد",
          "enable_gps": "تفعيل خدمات الموقع (GPS)",
          "track_last_orders": "متابعة اخر طلب",
          "ordered": "تم الطلب",
          "cancel_reason": "سبب الالغاء",
          "back": "رجوع",
          "profile": "حسابي",
          "no_canceled_orders": "لا يوجد طلبات ملغية",
          "biker_notes": "ملاحظات للبايكر",
          "Notes": "ملاحظات",
          "address_details": "تفاصيل العنوان",
          "select_ur_location": "حدد موقعك",
          "locate": "تحديد",
          "addresses": "العناوين",
          "credit_card": "بطاقة الإئتمان",
          "language": "اللغة",
          "change_car": "تغيير السيارة",
          "call_us": "اتصل علي",
          "terms": "سياسات التطبيق",
          "browse_as_visitor": "التصفح كزائر",
          "Please_login": "برجاء تسجيل الدخول",
          "chat": "المحادثة",
          "login_now": "سجل الآن",
          "deleteAccount": "هل تريد حذف الحساب ؟",
          "popularQ": "الاسئلة الشائعة",
          "profile_image": "الصورة الشخصية",
          "subCategory": "التصنيف الفرعي",
          "classification": "التصنيف",
          "Views": "المشاهدات",
          "ar_desc": "الوصف باللغة العربية",
          "contactUs": "تواصل معنا",
          "balance_due": "الرصيد المستحق",
          "subject": "الموضوع",
          "yourMessage": "اكتب رسالتك",
          "languageSwitch": "English",
          "welcome_to_d2020": "مرحبا بك في دليل D2020",
          "goToHome": "الذهاب إلى الرئيسية",
          "notifications": "الاشعارات",
          "information": "المعلومات",
          "times_of_work": "مواعيد العمل",
          "added_in": "تمت الإضافة في",
          "no_stores_in_account":
              "There are no creators in your account to display yet",
          "Add_a_facility": "اضف منشأه في حسابك الان واستمتع بأفضل العروض",
          "personal_info": "البيانات الشخصية",
          "soon": "هذه الخدمة ستكون متوفرة قريباً !",
          "family_onboarding": "مع قسم الاسر المنتجة",
          "delete_account": "حذف الحساب",
          "rental_onBoarding": "مع قسم الإيجار",
          "delegates_onboarding": "مع قسم المناديب",
          "sale_onboarding": "مع قسم البيع",
          "rents_filter": "تصفية الإيجارات",
          "product_details": "تفاصيل المنتج",
          "my_points": "نقاطي",
          "saved_places": "المواقع المحفوظة",
          "ok": "حسناً",
          "visa": "بطاقة إئتمان",
          "Schedule": "جدول مواعيد",
          "wash": "الغسلة",
          "productive_families": "الأسر المنتجة",
          "dark_mode": "الوضع الليلي",
          "family_desc": "اكبر تجمع لدعم وتمكين الأسر المنتجة",
          "add_rate": "أضف تقييمك",
          "country": "الدولة",
          "add_gifts_validation":
              "برجاء التأكد من اضافة قيمة الهدية والرسالة ورقم الهاتف ،الاسم",
          "sale": "البيع",
          "Search_products_for_sale": "بحث منتجات البيع",
          "Add_origin": "إضافة منشأه",
          "no_gifts": "لا يوجد هدايا حاليا",
          "yes": "نعم",
          "send_gifts": "إرسال الهدايا",
          "u_sure_to_logout": "هل انت متأكد من تسجيل الخروج ؟",
          "cancellation_reason": "سبب الإلغاء",
          "cancel": "إلغاء",
          "welcome": "أهلا بك",
          "gifts_phone": "إرسل الهدية لرقم هاتف  ",
          "fav": "المفضلة",
          "share_app": "مشاركة التطبيق",
          "share_app_message": "يمكنك مشاركة التطبيق مع اصدقائك",
          "share_now": "شارك الآن",
          "delegates": "المناديب",
          "delivery_notes":
              "ملاحظات : عزيزي المستخدم يرجى العلم ان عملية التوصيل من قبلنا ستستغرق من 2 يوم عمل الى 5 ايام عمل كحد اقصى",
          "whatsapp_reach": "توصل معنا عبر واتس اب",
          "Add_personal_photo": "إضافة صورة شخصية",
          "tax": "الضريبة",
          "cash": "كاشً",
          "distinguished_productive_families": "أسر منتجة متميزة",
          "my_cars": "سياراتي",
          "u_have": "لديك",
          "price_before_discount": "السعر قبل الخصم",
          "no_more_products": "ﻻ توجد منتجات اخرى",
          "no_more_notifications": "ﻻ توجد اشعارات اخرى",
          "add_new_address": "اضافة عنوان جديد",
          "swipe_up": "إسحب للأعلى",
          "notEmpty": "يجب أن تملأ البيانات",
          "best_sales": "أفضل المبيعات",
          "rent_type": "نوع الإيجار",
          "delete": "حذف",
          "add_site": "أضف موقع جديد",
          "noNotification": " لا يوجد إشعارات حالياً",
          "reason": "سبب الإلغاء",
          "noResult": "لا يوجد نتيجة !!!",
          "rate_sent": "تم ارسال تقييمك شكرا لك",
          "one_riyal_wash": "ريال للغسله الواحده",
          "no_order": "لا يوجد طلبات حالياً",
          "current_balance": "الرصيد الحالي",
          "saved": "تم الحفظ! من فضلك قم بإختيار حذف أو إرسال",
          "error": "خطأ!",
          "low_wallet_balance": "رصيد المحفظة لا يسمح",
          "choose_comp": "اختر",
          "update_profile": "تعديل الحساب",
          "get_new_password": "الحصول على كلمة مرور جديدة",
          "family_products": "منتجات الإسرة",
          "delivery_value": "الرسوم:",
          "use": "إستخدم",
          "login_validation_message": "برجاء التأكد من البيانات",
          "connectivity": "من فضلك قم بالاتصال بالانترنت",
          "choose_location": "اختر موقعك",
          "date_time": "التاريخ و الوقت",
          "no_notifications": "ليس لديك أي اشعار حتي الان",
          "available_times": "المواعيد المتاحة في هذا التاريخ",
          "termsAndConditions": "الشروط والأحكام",
          "replacementPolicies": "سياسة الإستبدال",
          "returnPolicies": "سياسة الإسترجاع",
          "show_location_map": "أظهر الموقع على الخريطة",
          "policies": "سياسات التطبيق",
          "enable_location": "برجاء تفعيل خاصية تحديد المكان فى الهاتف",
          "next": "التالي",
          "submit_order": "تأكيد الطلب",
          "your_location": 'موقعك',
          "rents_products": "منتجات الايجار",
          "car_volum": "حجم السيارة",
          "my_fatoora": "الفاتورة",
          "pay": "الدفع",
          "all": "الكل",
          "add_license": "إضافة تصريح",
          "add_location": "اضافة الموقع",
          "update": "تحديث",
          "enter_city": "أضف المدينة",
          "invoiceNumber": "رقم الفاتورة",
          "StepOne": "الخطوة الأولى",
          "notificationtype": "نوع الإشعار",
          "description": "الوصف",
          "date_and_time": "التاريخ و الوقت",
          "update_photo": "تحديث الصورة",
          "my_details": "التفاصيل",
          "select_payment_method": "اختر طريقة الدفع",
          "submit": "تأكيد",
          "notExist": "لا يوجد",
          "save_wash_price": "و وفر بسعر الغسله ",
          "exist": "يوجد",
          "giveLocationPermission": "من فضلك تأكد من تفعيل خاصية الموقع",
          "track": "تتبع",
          "Track": "التتبع",
          "communication": "التواصل",
          "cod_fees": "ر.د.عند الاستلام",
          "delivery_within": "التوصيل خلال",
          "day": "ايام",
          "shipping_fee": "سعر الشحن ",
          "recent_requests": "الطلبات الحديثة",
          "There_are_no_requests_yet": "لا يوجد طلبات حتي الان",
          "count": "العدد",
          "The_price_after_discount": 'السعر بعد الخصم',
          "enter_promo_code": "أدخل كوبون الخصم ...",
          'There_is_no_search_result': "لا يوجد نتيجة للبحث",
          "There_are_currently_no_ratings": "لا يوجد تصنيفات حاليا",
          "createAccount": "انشاء حساب",
          "wash_packages": " باقات الغسيل ",
          "enterInfo": "من فضلك أدخل اسمك والبريد الإلكتروني والرقم السري ",
          "success": "تمت العملية بنجاح !",
          "agree": "موافق",
          "agreeTerms": "يجب الموافقة على الشروط والأحكام",
          "goToWallet": "الذهاب إلى المحفظة",
          "login_with_bio": "الدخول بالبصمة",
          "en_name": "الاسم بالانجليزي",
          "loginWithApple": "الدخول بواسطة ابل",
          "update_store_images": "تعديل صورة المنشاة ",
          "enable_finger_print": "الدخول بالبصمة",
          "price": "السعر",
          "or": "او",
          "reservation_details": "تفاصيل الحجز ",
          "add_video": 'إضافة فيديو',
          "touch_to_use_wallet": "استخدام المحفظة للدفع",
          "enter_otp": "ادخل الـOTP",
          "userGuest": "استمر في التصفح كزائر",
          "registerNow": "يمكنك التسجيل الان",
          "Products": "المنتجات",
          "edit_store": "تعديل المنشأة",
          "car_brand": "ماركة السيارة",
          "For_rent": "للإيجار",
          "car_details": "تفاصيل السيارة",
          "whatsApp_contact": "التواصل عبر واتس اب",
          "Add_photos": "إضافة الصور",
          "English_title_(optional)": "العنوان انجليزي (إختياري)",
          "The_address_is_Arabic": "العنوان عربي",
          "sendSms": "سيتم الآن ارسال كود التفعيل الي الرقم",
          "sendEmail": "من فضلك ادخل كود التفعيل المرسل عبر البريد الإلكتروني",
          "hagVisa": "تأشيرة حج",
          "accepted": "تم القبول",
          "services": "الخدمات",
          "user": "مستخدم",
          "update_selling_product": "تحديث منتج للبيع",
          "counter_message": "يرجى تأكيد الطلب قبل الانتهاء من العداد",
          "optional": "اختياري",
          "Added_by": "تمت الإضافة بواسطة",
          "profilePic": "الصورة الشخصية",
          "my_wallet": "محفظتي",
          "add_product": "إضافة المنتج",
          "personalPhoto": "صورة شخصية",
          "add_image_validation": "الرجاء التأكد من إضافة الصور",
          "input_data_validation_message":
              'برجاء التأكد من إضافة البيانات صحيحة',
          "firstName": "الاسم الأول",
          "filter": "تصفية",
          "sale_filter": "تصفية البيع",
          "add_pics": "اضافة الصور",
          "photo_library": "معرض الصور",
          "cat_count": 'عدد الفئات',
          "have_gift": "لديك هدية ؟ قم بتطبيقها الآن",
          "family": "العائلة",
          "monthes": "شهور",
          "passportNo": "رقم الجواز",
          "gifts": "الهدايا",
          "dateOfBirth": "تاريخ الميلاد",
          "add_product_success_message": "تم إضافة المنتج بنجاح",
          "Category": "التصنيف",
          "account": "الحساب",
          "Add_car": "أضف سيارة",
          "placeOfBirth": "مكان الميلاد",
          "car_color": "لون السيارة",
          "plate_number": "رقم اللوحة",
          "en_desc": "الوصف باللغة الانجليزية (إختياري)",
          "nationalId": "رقم الهوية",
          "save_your_location": "حفظ موقعك",
          "nationality": "الجنسية",
          "all_packages": "جميع الباقات",
          "visaType": "نوع التأشيرة",
          "authority": "جهة الوصول",
          "distinction": "المميزات",
          "my_packages": "باقاتي",
          "message": "الرسالة",
          "recharge": " الشحن",
          "Communication_with_the_family": "التواصل مع الاسرة",
          "completeApplication": "استكمال الاستمارة",
          "no_pics_added": "لا يوجد صور مضافة",
          "add_more_images": "إضافة المريد من الصور",
          "car": "السيارة",
          "insuranceCompany": "اختر شركة تأمين",
          "ads_title": "عنوان الإعلان",
          "chooseCompany": "من فضلك قم باختيار شركة التامين المناسبة لك",
          "choosePhoto": "من فضلك قم باختيار صورتك الشخصية",
          "gifts2": "هدايا",
          "trips": "الرحلات",
          'suitable_price': "حسب المناسب لك",
          "essays": "المقالات",
          "enter_mount": "أدخل قيمة المبلغ المراد شحنه",
          "full_name": "الاسم كامل",
          "order_tracking": "تتبع الحجز",
          "in_d2020": "في دليل D2020",
          "essays2": "مقالات",
          "umrahOrder": "طلب عمرة",
          "biker_rate": "تقييمك للبايكر",
          "orderType": "نوع الطلب",
          "orderTracking": "تتبع الطلب",
          "delivery": "التوصيل",
          "cooking": "تجهيز",
          "goToMap": "الذهاب الي الخريطة",
          "addressName": "اسم العنوان",
          "forYou": "لنفسك",
          "info": "المعلومات",
          "forSomeOne": "لشخص اخر",
          "reservations": "الحجوزات",
          "UmrahInfo": "معلومات الشخص المراد العمرة له",
          "moreUmrahDetails": "تفاصيل أخرى (دعاء خاص بصاحب العمرة)",
          "umrahDetails": "تفاصيل العمرة",
          "search_for_location": "البحث عن موقعك",
          "offersFrom": "عروض المتاحة",
          "allCategories": "الأقسام",
          "latest_offers": 'احدث العروض و الخصومات',
          "Add_a_product_for_rent": "اضافة منتج للايجار",
          "Add_a_product_to_sell": "إضافة منتج للبيع",
          "edit_image": "تعديل الصورة",
          "Add_productive_family_product": "إضافة منتج أسرة منتجة",
          "what_we_offer": "ما الذي نقدمة",
          "It's_not_available_now": "لا يوجد حاليا",
          "accept": "قبول",
          "write_message": "اكتب رسالتك ..",
          "addProductRate": "أضف تقيمك",
          "give_your_location_name": "أعط موقعك أسم (منزل-عمل-الخ)",
          "noCartItems": "العربة فارغه",
          "orderDetails": "تفاصيل العروض",
          "serviceProviderProfile": "بيانات مقدم العرض",
          "drizzle_plus_wash": "غسيل دريزل بلس",
          "choose_localtion": "اختر الموقع",
          "current": "الحالية",
          "previous": "السابقة",
          "payment_details": "تفاصيل الدفع",
          "gift_value": "ادخل قيمه الهدية",
          "add_promo_code": "أضف كوبون الخصم",
          "previous_oper": "العمليات السابقة",
          "newArrival": "أحدث المنتجات",
          "add_store_msg2":
              "كل ما عليك التواصل مع خدمة عملاء الدليل عن طريق الواتساب او الاتصال و تزويدهم ببيانات المنشأة  ",
          "add_store_msg1":
              "يمكنك إضافة المنشأة الخاصة بك ( المحل الخاص بك ) في دليل 2020 التجاري بسهولة ..",
          "discount": "الخصم",
          "time": "وقت التصريح",
          "sell_desc": "بيع منتجاتك فى اكبر دليل",
          "age": "السن",
          "choose_care_model": "إختر موديل السيارة ",
          "reviews": "التقييمات",
          "change_language": "تغيير اللغة",
          "typeMessage": "اكتب رسالتك",
          "tripProvider": "القائم على الرحلة",
          "ordersNumber": "عدد الطلبات",
          "orders": "الطلبات",
          "reservation_number": "رقم الحجز",
          "chat": "محادثة",
          "essayDetails": "تفاصيل المقال",
          "badalUmrahOrder": "طلب عمرة بدل",
          "badalHajjOrder": "طلب حج بدل",
          "previous_Gifts": "الهدايا السابقة",
          "Shops_by_city": "محلات حسب المدينة ",
          "stores_filter": "تصفية المحلات",
          "noNotifications": "لا يوجد إشعارات حاليا",
          "noEssays": "لا يوجد مقالات حاليا",
          "tripsCounter": "عدد الرحلات",
          "add_new_car_hint": "اختر حجم و ماركة و موديل السيارة",
          "offerConfirmation": "هل انت متأكد من قبول العرض ؟",
          "offerAccepted": "تم قبول العرض بنجاح",
          "umrahFees": "رسوم العمرة",
          "travelingFees": "تكاليف الانتقال",
          "from": "من",
          "car_validations": "تأكد من إضافة السيارة",
          "time_date_validation": "تأكد من إضافة الوقت والتاريخ",
          "additional_services": "الخدمات الإضافية",
          "exit_app": "هل تريد الخروج من التطبيق؟",
          "to": "الي",
          "selectPayment": "من فضلك قم باختيار طريقة الدفع",
          "serviceFees": "رسوم الخدمة شاملة الضريبة",
          "state": "الحالة",
          "choose_another_times": "اختر تاريخاً آخر أو تحقق من أوقاتنا المخفضة",
          "biker_hint": "يمكن للبايكر أن يجد مركبتك أسهل دون الاتصال",
          "details": "التفاصيل",
          "my_facilities": "منشآتي",
          "from_time_to": 'من 10 صباحا : 12 مساءا',
          "It_is_closed_at_prayer_time": " إغلاق  وقت الصلاة",
          "orderDatails": "تفاصيل الطلب",
          "stores_search": "بحث المحلات",
          "report": "إبلاغ",
          "Yes": "نعم",
          "close": "إغلاق",
          "add_report": "إضافة تقرير",
          "reportReason": "سبب الإبلاغ",
          "Write_Your_Report": "أضف تقريرك",
          "done": "تم",
          "reported": "تم الإبلاغ",
          "canceledOrder": "إلغاء الطلب",
          "my_orders": "طلباتي",
          "waiting": "بإنتظار الموافقة",
          "package_details": "تفاصيل الباقة",
          "buy": "شراء",
          "sureToConfirm": "هل تريد تأكيد إستلام الخدمه ؟",
          "ehram": "الاحرام",
          "got_me": "وصلني",
          "no": "لا",
          "selling_products": "منتجات البيع",
          "the_closest": "الأقرب",
          "premium_places": "أماكن متميزة",
          "highest_rated": "الأعلى تقيماً",
          "Sortـby": "الترتيب حسب",
          "tawaf": "الطواف",
          "sayee": "السعي",
          "sonatTawaf": "سنة الطواف",
          "tahalol": "التحلل من الاحرام",
          "male": "ذكر",
          "female": "انثى",
          "view_update_account": "مشاهدة و تعديل الحساب",
          "guestUser": "دخول كزائر",
          "send_wash": "أرسل غسلات",
          "canLogin": "بإمكانك التسجيل الآن",
          "Containsـoffers": "يحتوي علي عروض",
          "family_filter_result": "نتيجة تصفية الاسر المنتجة",
          "check": "برجاء مراجعة البيانات",
          "orderReason": "سبب العمرة",
          "choosePayment": "اختر طريقة الدفع",
          "browse_D2020": "تصفح الدليل",
          "otherReason": "سبب آخر",
          "Shopkeeper": "صاحب محل",
          "downloadCertificate": "تحميل الشهادة",
          "wash": "غسيل",
          "garage": "الورش",
          "recovery": "نقل السيارات",
          "wheels": "الإطارات",
          "add_store": "إضافة المنشأة",
          "cars": "السيارات",
          "rentalOffices": "مكاتب التأجير",
          "rent": "الإيجار",
          "newest": "الأحدث",
          "minimum": "الحد الأدني",
          "spareParts": "قطع الغيار",
          "carPaint": "ألوان السيارة",
          "mechanical": "صيانة",
          "electrical": "كهرباء",
          "fixedServices": "خدمة من الجراج",
          "wash_fixed_services": "غسيل في الجراج",
          "wash_delivery_service": "غسيل في المنزل",
          "rental_office_name": "اسم مكتب التأجير",
          "deliveryService": "توصيل إلي المنزل",
          "accessories": "إكسسوارات",
          "user": "مستخدم",
          "no_results": "لاتوجد نتائج",
          "car_details": "تفاصيل السياره",
          "company": "شركة",
          "selectBundle": "من فضلك قم بإختيار باقة",
          "car_name": "اسم السيارة",
          "car_model": "طراز السيارة",
          "car_type": "نوع السيارة",
          "fill_form": "برجاء التأكد من ملئ جميع الحقول",
          "find_company": "بحث عن شركة",
          "request": "طلب",
          "available_cars": "السيارات المتاحة",
          "whats_app": "الواتس أب",
          "change_city": "تغيير المدينة",
          "dubai": "دبي",
          "abu_dhabi": "أبو ظبي",
          "sharjah": "الشارقة",
          "al_ain": "العين",
          "ajman": "عجمان",
          "ras_al_khaimah": "رأس الخيمة",
          "fujairah": "الفجيرة",
          "umm_al_quwain": "أم القيوين",
          "confirm_order": 'تأكيد الطلب',
          "dibba_al_fujairah": "دبا الفجيرة",
          "khor_fakkan": "خور فكان",
          "kalba": "كلباء",
          "jebel_ali": "جبل علي",
          "madinat_zayed": "مدينة زايد",
          "ruwais": "الروِيس",
          "liwa_oasis": "واحة ليوا",
          "dhaid": "الذيد",
          "ghayathi": "غِيَّاثِي",
          "ar_rams": "الرمس",
          "dibba_Al_hisn": "دبا الحصن",
          "hatta": "حتا",
          "search_car_mode": "بحث عن موديل السيارة",
          "al_madam": "المدام",
          "item_deleted": "تم الحذف بنجاح",
          "update_success": "تم التحديث بنجاح",
          "company_added_successfully": "تم إضافة الشركة بنجاح "
        }
      };
}
